# PostgresSQL
#   gem install sqlite3
#
#   Ensure the postgres gem is defined in your Gemfile
#   gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  database: ceyoung_pllc-development
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ceyoung_pllc-test
  pool: 5
  port: 5432
  host: localhost